runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /favicon.ico
    static_files: public/images/favicon.ico
    upload: public/images/favicon.ico
    secure: always
    login: admin

  # index files
  - url: /(.+)/
    static_files: public/\1/index.html
    upload: public/(.+)/index.html
    secure: always
    login: admin

  - url: /(.+)
    static_files: public/\1
    upload: public/(.*)
    secure: always
    login: admin

  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: always
    login: admin
