runtime: python27
api_version: 1
threadsafe: true

handlers:
  # index files
  - url: /(.+)/
    static_files: public/\1/index.html
    upload: public/(.+)/index.html
    secure: optional
    login: admin

  - url: /(.+)
    static_files: public/\1
    upload: public/(.*)
    secure: optional
    login: admin

  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: optional
    login: admin

