baseUrl = "https://www.gcppodcast.com"
languageCode = "en-us"
title = "Google Cloud Platform Podcast"

relativeURLs = true

paginate = 10

#Site Params
[params]
  description = "The Google Cloud Platform Podcast, coming to you every week. Discussing everything from on Google Cloud Platform from App Engine to Big Query."
  logo = "images/logo.png"
  twitterUser = "gcppodcast"
  twitterURL = "https://twitter.com/gcppodcast"
  googlePlusURL = "http://google.com/+gcppodcast"
  redditURL = "https://www.reddit.com/r/gcppodcast/"
  copyright = "Copyright 2015 Google Inc."
  episodeBucket = "https://eps-dot-gcppodcast.appspot.com/dl"
  rssFeed = "https://feeds.feedburner.com/GcpPodcast"
  itunesURL = "https://geo.itunes.apple.com/us/podcast"


[taxonomies]
  category = "categories"
  2015 = "2015" #http://discuss.gohugo.io/t/pagination-and-group-by-date/1441
  2016 = "2016"
  2017 = "2017"
